### ISSUE TITLE
ESM1.5 reconciliation: casa_rplant

### ISSUE THREAD

**Issue by JhanSrbinovsky** [CABLE-LSM/CABLE#273] opened 2024-04-24 02:38 UTC
Read only access to [TRAC ticket](https://trac.nci.org.au/trac/cable/ticket/362) raised by @rml599gh

**Comment by ccarouge** [comment] 2024-04-30 07:05
This is a duplicate of #163 which had been transferred from the TRAC system. I prefer keeping the transferred issue rather than this one that links to TRAC (since TRAC might disappear at some point).

**Closed by ccarouge** 2024-04-30 07:05 UTC
Labels: bug, quick, code clean-up
